Remove trailing semicolons (#156)

diff --git a/src/image/entrypoint b/src/image/entrypoint
--- a/src/image/entrypoint
+++ b/src/image/entrypoint
@@ -10,46 +10,46 @@ exec 4>/dev/null
 check_gosu() {
     command -v gosu && \
     gosu --version && \
-    gosu nobody true;
+    gosu nobody true
 }
 
 check_setpriv() {
     command -v setpriv && \
     setpriv --version && \
-    setpriv --reuid="$(id -u nobody)" --regid="$(id -g nobody)" --clear-groups true;
+    setpriv --reuid="$(id -u nobody)" --regid="$(id -g nobody)" --clear-groups true
 }
 
 # Split strings by a delimiter and extract an index. Uses space as a delimiter by default.
 extract_index() (
-    str="$1";
-    count="${2:-0}";
-    delimiter="${3:- }";
+    str="$1"
+    count="${2:-0}"
+    delimiter="${3:- }"
     while [ "$count" -gt 0 ]; do
-        : $((count -= 1));
+        : $((count -= 1))
         case "$str" in
             *${delimiter}*) str="${str#*${delimiter}}";;
             *) str='';;
         esac
     done
-    echo "${str%%${delimiter}*}";
+    echo "${str%%${delimiter}*}"
 )
 
 # Download a release file.
 # Args: release filename, output filename, release tag (defaults to latest release it not provided)
 download_file() {
     if [ $# -eq 3 ]; then
-        curl --fail -Ls -o "$2" "https://github.com/AJGranowski/docker-user-mirror/releases/download/${3}/${1}";
+        curl --fail -Ls -o "$2" "https://github.com/AJGranowski/docker-user-mirror/releases/download/${3}/${1}"
     elif [ $# -eq 2 ]; then
-        curl --fail -Ls -o "$2" "https://github.com/AJGranowski/docker-user-mirror/releases/latest/download/${1}";
+        curl --fail -Ls -o "$2" "https://github.com/AJGranowski/docker-user-mirror/releases/latest/download/${1}"
     else
-        echo 'Expected at least two arguments.' >&2;
-        return 1;
+        echo 'Expected at least two arguments.' >&2
+        return 1
     fi
 }
 
 # Query GitHub for the latest release tag.
 get_latest_release_tag() {
-    response="$(curl -Ls -w '%{http_code}' 'https://api.github.com/repos/AJGranowski/docker-user-mirror/releases/latest')";
+    response="$(curl -Ls -w '%{http_code}' 'https://api.github.com/repos/AJGranowski/docker-user-mirror/releases/latest')"
     case "$(echo "$response" | tail -1)" in
         2*)
             echo "$response" | \
@@ -64,21 +64,19 @@ get_latest_release_tag() {
 # Args: release tag (defaults to latest release it not provided)
 get_release_version() {
     if [ $# -eq 0 ]; then
-        response="$(curl -Ls -w '\n%{http_code}' 'https://github.com/AJGranowski/docker-user-mirror/releases/latest/download/version')";
+        response="$(curl -Ls -w '\n%{http_code}' 'https://github.com/AJGranowski/docker-user-mirror/releases/latest/download/version')"
     else
-        response="$(curl -Ls -w '\n%{http_code}' "https://github.com/AJGranowski/docker-user-mirror/releases/download/${1}/version")";
+        response="$(curl -Ls -w '\n%{http_code}' "https://github.com/AJGranowski/docker-user-mirror/releases/download/${1}/version")"
     fi
 
     case "$(echo "$response" | tail -1)" in
-        2*)
-            echo "$response" | head -1
-            ;;
+        2*) echo "$response" | head -1;;
         *) false;;
     esac
 }
 
 print_user() {
-    grep -e "^${1}:" /etc/passwd;
+    grep -e "^${1}:" /etc/passwd
 }
 
 # Query GitHub to check if a release tag exists.
@@ -92,40 +90,40 @@ release_tag_exists() {
 # Check for updates, and download the latest version.
 update() {
     if ! latest_version="$(get_release_version)"; then
-        echo 'Unable to fetch the latest version. Try again in a few minutes.' >&2;
-        return 1;
+        echo 'Unable to fetch the latest version. Try again in a few minutes.' >&2
+        return 1
     fi
 
     if [ "$VERSION" = "$latest_version" ]; then
-        echo 'Up to date.';
+        echo 'Up to date.'
     else
         if ! release_tag_exists "$(version_to_release_tag)"; then
-            echo 'Critical update required!';
+            echo 'Critical update required!'
             echo '    This version has been deleted, signaling either a critical bug or vulnerability. Update immediately.'
         else
             echo 'New update available.'
         fi
     fi
 
-    printf '    Current version: %s\n' "$VERSION";
-    printf '    Latest version:  %s\n' "$latest_version";
+    printf '    Current version: %s\n' "$VERSION"
+    printf '    Latest version:  %s\n' "$latest_version"
 
     if [ "$VERSION" = "$latest_version" ]; then
-        return 0;
+        return 0
     fi
 
     if [ "$o_yes" != true ]; then
-        echo '\nInstall the update? (y/n)';
-        read yn;
+        echo '\nInstall the update? (y/n)'
+        read yn
         case "$yn" in
             y*) ;;
             n*) return 0;;
         esac
     fi
 
-    echo 'Installing update...';
-    download_file 'entrypoint' "${0}.tmp";
-    mv "${0}.tmp" "$0" && chmod +x "$0" && printf '%s installed!\n' "$latest_version"; exit 0;
+    echo 'Installing update...'
+    download_file 'entrypoint' "${0}.tmp"
+    mv "${0}.tmp" "$0" && chmod +x "$0" && printf '%s installed!\n' "$latest_version"; exit 0
 }
 
 # Convert "$VERSION" to "release-**" format.
@@ -141,64 +139,64 @@ version_to_release_tag() {
 while [ $# -gt 0 ]; do
     case "$1" in
         --setup)
-            o_setup=true;
+            o_setup=true
             ;;
         --update)
-            o_update=true;
+            o_update=true
             ;;
         --verbose)
-            exec 3>&1;
-            exec 4>&2;
+            exec 3>&1
+            exec 4>&2
             ;;
         --version)
-            printf 'Version: %s\n' "$VERSION";
-            exit 0;
+            printf 'Version: %s\n' "$VERSION"
+            exit 0
             ;;
         -y|--yes)
-            o_yes=true;
+            o_yes=true
             ;;
         --)
-            shift;
-            break;
+            shift
+            break
             ;;
         *) break;;
     esac
-    shift;
+    shift
 done
 
 if [ "$o_update" = true ]; then
     if update; then
-        exit 0;
+        exit 0
     else
-        exit 1;
+        exit 1
     fi
 fi
 
 if [ "$o_setup" = true ]; then
-    set -euxC;
+    set -euxC
 
     if ! check_setpriv >/dev/null 2>&1; then
-        echo 'setpriv is not installed or is out of date. Attempting to install setpriv...';
+        echo 'setpriv is not installed or is out of date. Attempting to install setpriv...'
 
         # Attempt to install setpriv with apk.
         if (apk update && apk -s add setpriv) >/dev/null 2>&1; then
-            apk add --no-cache "setpriv>=${SETPRIV_VERSION}";
-            hash -r;
-            check_setpriv;
-            echo 'setpriv installed!';
+            apk add --no-cache "setpriv>=${SETPRIV_VERSION}"
+            hash -r
+            check_setpriv
+            echo 'setpriv installed!'
 
         # Attempt to install setpriv from util-linux with apt-get.
         elif (apt-get update && apt-get install --dry-run util-linux) >/dev/null 2>&1; then
-            apt-get satisfy --no-install-recommends -y "util-linux (>=${UTIL_LINUX_VERSION})";
-            hash -r;
-            check_setpriv;
-            echo 'setpriv installed!';
+            apt-get satisfy --no-install-recommends -y "util-linux (>=${UTIL_LINUX_VERSION})"
+            hash -r
+            check_setpriv
+            echo 'setpriv installed!'
 
         # Attempt to install gosu as a fallback.
         elif ! check_gosu >/dev/null 2>&1; then
-            echo 'gosu is not installed or is out of date. Attempting to install gosu...';
+            echo 'gosu is not installed or is out of date. Attempting to install gosu...'
 
-            unameArch="$(uname -m)";
+            unameArch="$(uname -m)"
             case "$unameArch" in
                 aarch64) dpkgArch='arm64' ;;
                 armv[67]*) dpkgArch='armhf' ;;
@@ -209,126 +207,126 @@ if [ "$o_setup" = true ]; then
                 *) printf 'error: unknown/unsupported architecture: %s\n' "$unameArch" >&2; exit 1;;
             esac
 
-            mkdir -p /usr/local/bin/;
-            wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${dpkgArch}";
-            wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${dpkgArch}.asc";
+            mkdir -p /usr/local/bin/
+            wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${dpkgArch}"
+            wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${dpkgArch}.asc"
 
-            GNUPGHOME="$(mktemp -d)";
+            GNUPGHOME="$(mktemp -d)"
             if command -v gpg >/dev/null; then
-                gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4;
-                gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu;
-                gpgconf --kill all;
+                gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
+                gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu
+                gpgconf --kill all
             fi
-            rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc;
-            chmod +x /usr/local/bin/gosu;
-            check_gosu;
+            rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc
+            chmod +x /usr/local/bin/gosu
+            check_gosu
         fi
     fi
 else
-    set -eC;
+    set -eC
 
     if [ -z "$USER_MIRROR_HOST_USER" ]; then
-        echo 'USER_MIRROR_HOST_USER is unset' >&2;
-        guard_failure=true;
+        echo 'USER_MIRROR_HOST_USER is unset' >&2
+        guard_failure=true
     fi
 
     if [ "$guard_failure" = true ]; then
-        exit 1;
+        exit 1
     fi
 
-    printf 'USER_MIRROR_CAPABILITIES=%s\n' "$USER_MIRROR_CAPABILITIES" >&3;
-    printf 'USER_MIRROR_HOST_USER=%s\n' "$USER_MIRROR_HOST_USER" >&3;
-    printf 'USER_MIRROR_SERVICE_NAME=%s\n' "$USER_MIRROR_SERVICE_NAME" >&3;
+    printf 'USER_MIRROR_CAPABILITIES=%s\n' "$USER_MIRROR_CAPABILITIES" >&3
+    printf 'USER_MIRROR_HOST_USER=%s\n' "$USER_MIRROR_HOST_USER" >&3
+    printf 'USER_MIRROR_SERVICE_NAME=%s\n' "$USER_MIRROR_SERVICE_NAME" >&3
 
-    host_user_name="$(extract_index "$USER_MIRROR_HOST_USER" 0 ':')";
-    host_user_id="$(extract_index "$USER_MIRROR_HOST_USER" 1 ':')";
-    host_user_group="$(extract_index "$USER_MIRROR_HOST_USER" 2 ':')";
-    host_user_gid="$(extract_index "$USER_MIRROR_HOST_USER" 3 ':')";
+    host_user_name="$(extract_index "$USER_MIRROR_HOST_USER" 0 ':')"
+    host_user_id="$(extract_index "$USER_MIRROR_HOST_USER" 1 ':')"
+    host_user_group="$(extract_index "$USER_MIRROR_HOST_USER" 2 ':')"
+    host_user_gid="$(extract_index "$USER_MIRROR_HOST_USER" 3 ':')"
 
     # Create/replace user if non-root.
     if [ "$host_user_id" -ne 0 ] && [ "$host_user_name" != 'root' ]; then
-        export SHELL='/bin/sh';
+        export SHELL='/bin/sh'
 
-        uid_username="$(awk -F: "\$3 == ${host_user_id} {print \$1}" /etc/passwd)";
+        uid_username="$(awk -F: "\$3 == ${host_user_id} {print \$1}" /etc/passwd)"
         if id -u "$uid_username" >/dev/null 2>&1; then
-            printf 'Removing user matching UID %s: %s\n' "$host_user_id" "$(print_user "$uid_username")" >&3;
+            printf 'Removing user matching UID %s: %s\n' "$host_user_id" "$(print_user "$uid_username")" >&3
             if command -v userdel >/dev/null; then
-                userdel "$uid_username";
+                userdel "$uid_username"
             else
-                deluser "$uid_username" 2>/dev/null;
+                deluser "$uid_username" 2>/dev/null
             fi
         fi
 
         if command -v groupadd >/dev/null; then
-            groupadd -g "$host_user_gid" "$host_user_group" || true;
+            groupadd -g "$host_user_gid" "$host_user_group" || true
         else
-            addgroup -g "$host_user_gid" "$host_user_group" || true;
+            addgroup -g "$host_user_gid" "$host_user_group" || true
         fi
-        gid_groupname="$(awk -F: "\$3 == ${host_user_gid} {print \$1}" /etc/group)";
+        gid_groupname="$(awk -F: "\$3 == ${host_user_gid} {print \$1}" /etc/group)"
 
         if command -v useradd >/dev/null; then
-            useradd -c 'Mirrored Host User' -g "$host_user_gid" -m -s "$SHELL" -u "$host_user_id" "$host_user_name" 2>&4;
+            useradd -c 'Mirrored Host User' -g "$host_user_gid" -m -s "$SHELL" -u "$host_user_id" "$host_user_name" 2>&4
         else
-            adduser -D -g 'Mirrored Host User' -G "$gid_groupname" -s "$SHELL" -u "$host_user_id" "$host_user_name" 2>&4;
+            adduser -D -g 'Mirrored Host User' -G "$gid_groupname" -s "$SHELL" -u "$host_user_id" "$host_user_name" 2>&4
         fi
-        printf 'Created user: %s\n' "$(print_user "$host_user_name")" >&3;
+        printf 'Created user: %s\n' "$(print_user "$host_user_name")" >&3
 
-        export HOME="/home/${host_user_name}";
+        export HOME="/home/${host_user_name}"
     else
-        export HOME='/root';
+        export HOME='/root'
     fi
 
-    export LOGNAME="$host_user_name";
-    export USER="$host_user_name";
+    export LOGNAME="$host_user_name"
+    export USER="$host_user_name"
 
     # Set the ownership of a set of items to the user.
     while read service_name; do
         if [ -z "$service_name" ]; then
-            continue;
+            continue
         fi
 
         case "$service_name" in
             /*)
-                chown_path="$service_name";
-                unset service_name;
+                chown_path="$service_name"
+                unset service_name
                 ;;
             *) read chown_path;;
         esac
 
         if [ -n "$service_name" ] && [ "$service_name" != "$USER_MIRROR_SERVICE_NAME" ]; then
-            continue;
+            continue
         fi
 
         if [ ! -e "$chown_path" ]; then
-            printf "cannot access '%s': No such file or directory\n" "$chown_path" >&4;
-            continue;
+            printf "cannot access '%s': No such file or directory\n" "$chown_path" >&4
+            continue
         fi
 
-        chown -c "${host_user_id}:${host_user_gid}" "$chown_path" >&3;
+        chown -c "${host_user_id}:${host_user_gid}" "$chown_path" >&3
     done <<EOF
 $USER_MIRROR_CHOWN_LIST
 EOF
 
     if [ -n "$USER_MIRROR_CAPABILITIES" ]; then
-        capabilities="-all,$USER_MIRROR_CAPABILITIES";
+        capabilities="-all,$USER_MIRROR_CAPABILITIES"
     else
-        capabilities='-all';
+        capabilities='-all'
     fi
 
-    unset USER_MIRROR_CAPABILITIES;
-    unset USER_MIRROR_CHOWN_LIST;
-    unset USER_MIRROR_HOST_USER;
-    unset USER_MIRROR_SERVICE_NAME;
+    unset USER_MIRROR_CAPABILITIES
+    unset USER_MIRROR_CHOWN_LIST
+    unset USER_MIRROR_HOST_USER
+    unset USER_MIRROR_SERVICE_NAME
 
     # Execute using $HOST_MAPPED_UID.
     if check_setpriv >/dev/null 2>&1; then
-        echo "exec setpriv --bounding-set \"${capabilities}\" --init-groups --no-new-privs --reuid=${host_user_id} --regid=${host_user_gid} ..." >&3;
-        exec setpriv --bounding-set "$capabilities" --init-groups --no-new-privs --reuid=${host_user_id} --regid=${host_user_gid} "$@";
+        echo "exec setpriv --bounding-set \"${capabilities}\" --init-groups --no-new-privs --reuid=${host_user_id} --regid=${host_user_gid} ..." >&3
+        exec setpriv --bounding-set "$capabilities" --init-groups --no-new-privs --reuid=${host_user_id} --regid=${host_user_gid} "$@"
     elif command -v gosu >/dev/null; then
-        echo "exec gosu \"${host_user_id}:${host_user_gid}\" ..." >&3;
-        exec gosu "${host_user_id}:${host_user_gid}" "$@";
+        echo "exec gosu \"${host_user_id}:${host_user_gid}\" ..." >&3
+        exec gosu "${host_user_id}:${host_user_gid}" "$@"
     else
-        printf 'Unable to set user\n' >&2;
-        exit 1;
+        printf 'Unable to set user\n' >&2
+        exit 1
     fi
 fi
diff --git a/test/create-source-path-test b/test/create-source-path-test
--- a/test/create-source-path-test
+++ b/test/create-source-path-test
@@ -1,13 +1,13 @@
 #!/bin/sh
-THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
-. "$THIS_SCRIPT_DIR/../scripts/test-utilities";
+THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
+. "$THIS_SCRIPT_DIR/../scripts/test-utilities"
 
 # Skip on Podman
 if [ "$CONTAINER_ENGINE" = 'podman' ]; then
-    exit 0;
+    exit 0
 fi
 
-mv compose.yml compose1.yml;
+mv compose.yml compose1.yml
 cat <<EOF > compose2.yml
 services:
   sh:
@@ -26,21 +26,21 @@ services:
           create_host_path: false
 EOF
 
-$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config > compose.yml;
-rm compose1.yml;
-rm compose2.yml;
+$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config > compose.yml
+rm compose1.yml
+rm compose2.yml
 
-$COMPOSE_ENGINE build;
+$COMPOSE_ENGINE build
 if ./user-mirror $COMPOSE_ENGINE run --rm sh -c 'true' 2>/dev/null; then
-    printf 'Run succeeded when it should have failed (expected failure when do-not-create.file does not exist)' >&2;
-    exit 1;
+    printf 'Run succeeded when it should have failed (expected failure when do-not-create.file does not exist)' >&2
+    exit 1
 fi
 
-mkdir do-not-create;
-./user-mirror $COMPOSE_ENGINE run --rm sh -c 'true';
+mkdir do-not-create
+./user-mirror $COMPOSE_ENGINE run --rm sh -c 'true'
 
 # Test directory exists
 if ! [ -d create ]; then
-    printf 'directory "%s" not found\n' 'create' >&2;
-    exit 1;
+    printf 'directory "%s" not found\n' 'create' >&2
+    exit 1
 fi
diff --git a/test/mkdir-test b/test/mkdir-test
--- a/test/mkdir-test
+++ b/test/mkdir-test
@@ -1,26 +1,26 @@
 #!/bin/sh
-THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
-. "$THIS_SCRIPT_DIR/../scripts/test-utilities";
+THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
+. "$THIS_SCRIPT_DIR/../scripts/test-utilities"
 
-$COMPOSE_ENGINE build;
-./user-mirror $COMPOSE_ENGINE run --rm sh -c 'mkdir dir';
+$COMPOSE_ENGINE build
+./user-mirror $COMPOSE_ENGINE run --rm sh -c 'mkdir dir'
 
 # Test directory exists
 if ! [ -d dir ]; then
-    printf 'directory "%s" not found\n' 'dir' >&2;
-    exit 1;
+    printf 'directory "%s" not found\n' 'dir' >&2
+    exit 1
 fi
 
 # Test file ownership matches the current user
-directory_owner_uid=$(stat -c "%u" dir);
-directory_owner_gid=$(stat -c "%g" dir);
-user_uid=$(id -u);
-user_gid=$(id -g);
+directory_owner_uid=$(stat -c "%u" dir)
+directory_owner_gid=$(stat -c "%g" dir)
+user_uid=$(id -u)
+user_gid=$(id -g)
 if ! [ $directory_owner_uid -eq $user_uid ]; then
-    printf 'Ownership UID for "dir" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2;
-    exit 1;
+    printf 'Ownership UID for "dir" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2
+    exit 1
 fi
 if ! [ $directory_owner_gid -eq $user_gid ]; then
-    printf 'Ownership GID for "dir" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2;
-    exit 1;
+    printf 'Ownership GID for "dir" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2
+    exit 1
 fi
diff --git a/test/nested-bind-test b/test/nested-bind-test
--- a/test/nested-bind-test
+++ b/test/nested-bind-test
@@ -1,8 +1,8 @@
 #!/bin/sh
-THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
-. "$THIS_SCRIPT_DIR/../scripts/test-utilities";
+THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
+. "$THIS_SCRIPT_DIR/../scripts/test-utilities"
 
-mv compose.yml compose1.yml;
+mv compose.yml compose1.yml
 cat <<EOF > compose2.yml
 services:
   sh:
@@ -12,31 +12,31 @@ services:
         target: /docker-user-mirror/.npmrc
 EOF
 
-$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config > compose.yml;
-rm compose1.yml;
-rm compose2.yml;
+$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config > compose.yml
+rm compose1.yml
+rm compose2.yml
 
-touch docker.npmrc;
+touch docker.npmrc
 
-$COMPOSE_ENGINE build;
-./user-mirror $COMPOSE_ENGINE run --rm sh -c 'true';
+$COMPOSE_ENGINE build
+./user-mirror $COMPOSE_ENGINE run --rm sh -c 'true'
 
 # Test file exists
 if ! [ -f .npmrc ]; then
-    printf 'file "%s" not found\n' '.npmrc' >&2;
-    exit 1;
+    printf 'file "%s" not found\n' '.npmrc' >&2
+    exit 1
 fi
 
 # Test file ownership matches the current user
-file_owner_uid=$(stat -c "%u" .npmrc);
-file_owner_gid=$(stat -c "%g" .npmrc);
-user_uid=$(id -u);
-user_gid=$(id -g);
+file_owner_uid=$(stat -c "%u" .npmrc)
+file_owner_gid=$(stat -c "%g" .npmrc)
+user_uid=$(id -u)
+user_gid=$(id -g)
 if ! [ $file_owner_uid -eq $user_uid ]; then
-    printf 'Ownership UID for ".npmrc" does not match (expected %s, got %s)\n' $user_uid $file_owner_uid >&2;
-    exit 1;
+    printf 'Ownership UID for ".npmrc" does not match (expected %s, got %s)\n' $user_uid $file_owner_uid >&2
+    exit 1
 fi
 if ! [ $file_owner_gid -eq $user_gid ]; then
-    printf 'Ownership GID for ".npmrc" does not match (expected %s, got %s)\n' $user_gid $file_owner_gid >&2;
-    exit 1;
+    printf 'Ownership GID for ".npmrc" does not match (expected %s, got %s)\n' $user_gid $file_owner_gid >&2
+    exit 1
 fi
