Add update function to entrypoint

diff --git a/src/image/entrypoint b/src/image/entrypoint
--- a/src/image/entrypoint
+++ b/src/image/entrypoint
@@ -18,8 +18,107 @@ check_setpriv() {
     setpriv --reuid="$(id -u nobody)" --regid="$(id -g nobody)" --clear-groups true;
 }
 
+# Download a release file.
+# Args: release filename, output filename, release tag (defaults to latest release it not provided)
+download_file() {
+    if [ $# -eq 3 ]; then
+        curl --fail -Ls -o "$2" "https://github.com/AJGranowski/docker-user-mirror/releases/download/$3/$1";
+    elif [ $# -eq 2 ]; then
+        curl --fail -Ls -o "$2" "https://github.com/AJGranowski/docker-user-mirror/releases/latest/download/$1";
+    else
+        echo 'Expected at least two arguments.' >&2;
+        return 1;
+    fi
+}
+
+# Query GitHub for the latest release tag.
+get_latest_release_tag() {
+    response="$(curl -Ls -w '%{http_code}' 'https://api.github.com/repos/AJGranowski/docker-user-mirror/releases/latest')";
+    case "$(echo "$response" | tail -1)" in
+        2*)
+            echo "$response" | \
+            grep -E '^\s*"tag_name":' | \
+            sed -E 's/.*"tag_name": "([^"]+)".*/\1/g'
+        ;;
+        *) false;;
+    esac
+}
+
+# Get the version ID of a release.
+# Args: release tag (defaults to latest release it not provided)
+get_release_version() {
+    if [ $# -eq 0 ]; then
+        response="$(curl -Ls -w '\n%{http_code}' 'https://github.com/AJGranowski/docker-user-mirror/releases/latest/download/version')";
+    else
+        response="$(curl -Ls -w '\n%{http_code}' "https://github.com/AJGranowski/docker-user-mirror/releases/download/$1/version")";
+    fi
+
+    case "$(echo "$response" | tail -1)" in
+        2*)
+            echo "$response" | head -1
+            ;;
+        *) false;;
+    esac
+}
+
 print_user() {
     grep -e "^$1:" /etc/passwd;
+}
+
+# Query GitHub to check if a release tag exists.
+release_tag_exists() {
+    case "$(curl -Ls -o /dev/null -w '%{http_code}' "https://api.github.com/repos/AJGranowski/docker-user-mirror/releases/tags/$1")" in
+        2*) true;;
+        *) false;;
+    esac
+}
+
+# Check for updates, and download the latest version.
+update() {
+    if ! latest_version="$(get_release_version)"; then
+        echo 'Unable to fetch the latest version. Try again in a few minutes.' >&2;
+        return 1;
+    fi
+
+    if [ "$VERSION" = "$latest_version" ]; then
+        echo 'Up to date.';
+    else
+        if ! release_tag_exists "$(version_to_release_tag)"; then
+            echo 'Critical update required!';
+            echo '    This version has been deleted, signalling either a critical bug or vulnerability. Update immediately.'
+        else
+            echo 'New update available.'
+        fi
+    fi
+
+    echo "    Current version: $VERSION";
+    echo "    Latest version:  $latest_version";
+
+    if [ "$VERSION" = "$latest_version" ]; then
+        return 0;
+    fi
+
+    if [ "$o_yes" != true ]; then
+        echo '\nInstall the update? (y/n)';
+        read yn;
+        case $yn in
+            y*) ;;
+            n*) return 0;;
+        esac
+    fi
+
+    download_file "$(basename "$0")" "${0}.tmp";
+    mv "${0}.tmp" "$0";
+    exit 0;
+}
+
+# Convert "$VERSION" to "release-**" format.
+version_to_release_tag() {
+    if [ $# -eq 0 ]; then
+        echo "$VERSION" | sed -E 's/([^-]*).*/release-\1/g'
+    else
+        echo "$1" | sed -E 's/([^-]*).*/release-\1/g'
+    fi
 }
 
 # Parse options.
@@ -32,9 +131,15 @@ while [ $# -gt 0 ]; do
             exec 3>&1;
             o_setup=true;
             ;;
+        --update)
+            o_update=true;
+            ;;
         --version)
             echo "Version: ${VERSION}";
             exit 0;
+            ;;
+        -y|--yes)
+            o_yes=true;
             ;;
         --)
             shift;
@@ -46,6 +151,14 @@ while [ $# -gt 0 ]; do
     esac
     shift;
 done
+
+if [ "$o_update" = true ]; then
+    if update; then
+        exit 0;
+    else
+        exit 1;
+    fi
+fi
 
 if [ "$o_setup" = true ]; then
     set -euxC;
@@ -120,7 +233,7 @@ else
         guard_failure=true;
     fi
 
-    if [ "$guard_failure" = 'true' ]; then
+    if [ "$guard_failure" = true ]; then
         exit 1;
     fi
 
