Add ownership property

diff --git a/src/image/entrypoint b/src/image/entrypoint
--- a/src/image/entrypoint
+++ b/src/image/entrypoint
@@ -285,13 +285,27 @@ else
             continue
         fi
 
+        read ownership
+        read chown_path
+
         case "$service_name" in
-            /*)
-                chown_path="$service_name"
-                unset service_name
-                ;;
-            *) read chown_path;;
+            S:*) service_name="${service_name#S:}";;
+            *) error=1;;
         esac
+
+        case "$ownership" in
+            O:*) ownership="${ownership#O:}";;
+            *) error=1
+        esac
+
+        case "$chown_path" in
+            P:*) chown_path="${chown_path#P:}";;
+            *) error=1
+        esac
+
+        if [ -n "$error" ]; then
+            printf 'error: invalid chown list object: {%s, %s, %s}\n' "$service_name" >&2; exit 1;;
+        fi
 
         if [ -n "$service_name" ] && [ "$service_name" != "$USER_MIRROR_SERVICE_NAME" ]; then
             continue
