Skip matrix iteration if variable already set

diff --git a/ci b/ci
--- a/ci
+++ b/ci
@@ -9,8 +9,5 @@ if command -v shellcheck >/dev/null; then
     echo 'Shellcheck passed!');
 fi
 
-if [ -z "$COMPOSE_ENGINE" ]; then
-    (cd "$THIS_SCRIPT_DIR" && ./scripts/matrix-compose-engine scripts/matrix-images scripts/matrix-test-suite scripts/run-test);
-else
-    (cd "$THIS_SCRIPT_DIR" && COMPOSE_ENGINE="$COMPOSE_ENGINE" ./scripts/matrix-images scripts/matrix-test-suite scripts/run-test);
-fi && (echo 'All test pass!' || (echo 'Test failure.' >&2 && false));
+(cd "$THIS_SCRIPT_DIR" && ./scripts/matrix-images scripts/matrix-test-suite scripts/run-test) && \
+(echo 'All test pass!' || (echo 'Test failure.' >&2 && false));
