Remove trailing semicolons

diff --git a/ci b/ci
--- a/ci
+++ b/ci
@@ -1,13 +1,13 @@
 #!/bin/sh
-set -eC;
+set -eC
 
-THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
+THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
 
 if command -v shellcheck >/dev/null; then
     (cd "$THIS_SCRIPT_DIR" && \
     grep -e '^#!/bin/sh' --exclude-dir=.git -lR | xargs shellcheck --shell=sh --severity=warning && \
-    echo 'Shellcheck passed!');
+    echo 'Shellcheck passed!')
 fi
 
 (cd "$THIS_SCRIPT_DIR" && ./scripts/matrix-images scripts/matrix-test-suite scripts/run-test) && \
-(echo 'All test pass!' || (echo 'Test failure.' >&2 && false));
+(echo 'All test pass!' || (echo 'Test failure.' >&2 && false))
diff --git a/scripts/run-test b/scripts/run-test
--- a/scripts/run-test
+++ b/scripts/run-test
@@ -1,86 +1,86 @@
 #!/bin/sh
-set -eC;
+set -eC
 
 # Prerequisite check
 if ! command -v realpath >/dev/null; then
-    printf '%s\n' 'realpath command not found' >&2;
-    exit 1;
+    printf '%s\n' 'realpath command not found' >&2
+    exit 1
 fi
 
 if [ ! -f /proc/sys/kernel/random/uuid ]; then
-    printf '%s\n' '/proc/sys/kernel/random/uuid not found' >&2;
-    exit 1;
+    printf '%s\n' '/proc/sys/kernel/random/uuid not found' >&2
+    exit 1
 fi
 
 uuid() {
-    cat /proc/sys/kernel/random/uuid;
+    cat /proc/sys/kernel/random/uuid
 }
 
 # Full path to this script
-THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
-SRC_DIR="$(realpath "$THIS_SCRIPT_DIR/../src")";
+THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
+SRC_DIR="$(realpath "$THIS_SCRIPT_DIR/../src")"
 
 # Full path to the test script
-TEST_SCRIPT_PATH="$(realpath "$1")";
-shift;
+TEST_SCRIPT_PATH="$(realpath "$1")"
+shift
 
 if [ -z "$COMPOSE_ENGINE" ]; then
-    COMPOSE_ENGINE="docker compose";
+    COMPOSE_ENGINE="docker compose"
 fi
 
 if [ -z "$DOCKERFILE_PATH" ]; then
-    DOCKERFILE_PATH="$(realpath "$THIS_SCRIPT_DIR/../images/alpine/Dockerfile")";
+    DOCKERFILE_PATH="$(realpath "$THIS_SCRIPT_DIR/../images/alpine/Dockerfile")"
 fi
 
 if [ -z "$TESTING_ENVIRONMENT_DIR" ]; then
-    TESTING_ENVIRONMENT_DIR="$(realpath "$THIS_SCRIPT_DIR/../bin")";
+    TESTING_ENVIRONMENT_DIR="$(realpath "$THIS_SCRIPT_DIR/../bin")"
 fi
 
 case $COMPOSE_ENGINE in
     docker*)
-        CONTAINER_ENGINE='docker';
+        CONTAINER_ENGINE='docker'
         ;;
     podman*)
-        CONTAINER_ENGINE='podman';
+        CONTAINER_ENGINE='podman'
         ;;
 esac
 
 # Create the test namespace
-test_dir="$TESTING_ENVIRONMENT_DIR/$(uuid)";
-mkdir -p "$test_dir";
+test_dir="$TESTING_ENVIRONMENT_DIR/$(uuid)"
+mkdir -p "$test_dir"
 
 # Create the image build context
-image_dir="$test_dir/image";
-mkdir -p "$image_dir";
-cp "$SRC_DIR/image/Dockerfile.user-mirror" "$image_dir/Dockerfile";
-cp "$DOCKERFILE_PATH" "$image_dir/Dockerfile.base-image";
-printf '\n' >> "$image_dir/Dockerfile.base-image";
-(cd "$image_dir" && sed -i -e '/#{{Dockerfile}}/{r Dockerfile.base-image' -e 'd;}' Dockerfile);
-rm "$image_dir/Dockerfile.base-image";
-cp "$SRC_DIR/image/entrypoint" "$image_dir";
+image_dir="$test_dir/image"
+mkdir -p "$image_dir"
+cp "$SRC_DIR/image/Dockerfile.user-mirror" "$image_dir/Dockerfile"
+cp "$DOCKERFILE_PATH" "$image_dir/Dockerfile.base-image"
+printf '\n' >> "$image_dir/Dockerfile.base-image"
+(cd "$image_dir" && sed -i -e '/#{{Dockerfile}}/{r Dockerfile.base-image' -e 'd;}' Dockerfile)
+rm "$image_dir/Dockerfile.base-image"
+cp "$SRC_DIR/image/entrypoint" "$image_dir"
 
 # Create the image runtime context
-cp "$SRC_DIR/compose.yml" "$test_dir";
-cp "$SRC_DIR/user-mirror" "$test_dir";
+cp "$SRC_DIR/compose.yml" "$test_dir"
+cp "$SRC_DIR/user-mirror" "$test_dir"
 
 # Run the test
-echo "[run-test] Running $(basename "$TEST_SCRIPT_PATH") on $(basename "$(dirname "$DOCKERFILE_PATH")") with $COMPOSE_ENGINE... ($(basename "$test_dir"))";
+echo "[run-test] Running $(basename "$TEST_SCRIPT_PATH") on $(basename "$(dirname "$DOCKERFILE_PATH")") with $COMPOSE_ENGINE... ($(basename "$test_dir"))"
 if (cd "$test_dir" && COMPOSE_ENGINE="$COMPOSE_ENGINE" CONTAINER_ENGINE="$CONTAINER_ENGINE" $TEST_SCRIPT_PATH "$@"); then
-    test_status='success';
+    test_status='success'
 else
-    test_status='failure';
+    test_status='failure'
 fi
 
 # Remove the image
-(cd "$test_dir" && $COMPOSE_ENGINE down --rmi local 2>/dev/null) || true;
-($CONTAINER_ENGINE rm "$(basename "$TEST_SCRIPT_PATH")" 2>/dev/null) || true;
+(cd "$test_dir" && $COMPOSE_ENGINE down --rmi local 2>/dev/null) || true
+($CONTAINER_ENGINE rm "$(basename "$TEST_SCRIPT_PATH")" 2>/dev/null) || true
 
 if [ "$test_status" != 'success' ]; then
-    false;
+    false
 fi
 
 # Remove the test namespace
-rm -rf -- "$test_dir" || sudo rm -rf -- "$test_dir";
+rm -rf -- "$test_dir" || sudo rm -rf -- "$test_dir"
 
 # Remove the test environment if it's empty
-rm -d -- "$TESTING_ENVIRONMENT_DIR" 2>/dev/null || true;
+rm -d -- "$TESTING_ENVIRONMENT_DIR" 2>/dev/null || true
diff --git a/test/base-cli-volume-host-test b/test/base-cli-volume-host-test
--- a/test/base-cli-volume-host-test
+++ b/test/base-cli-volume-host-test
@@ -1,27 +1,27 @@
 #!/bin/sh
-THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
-. "$THIS_SCRIPT_DIR/../scripts/test-utilities";
+THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
+. "$THIS_SCRIPT_DIR/../scripts/test-utilities"
 
-IMAGE_NAME="$(pwd | xargs basename)";
-$CONTAINER_ENGINE build -t "$IMAGE_NAME" image/;
-./user-mirror $CONTAINER_ENGINE run --rm -v ./:/docker-user-mirror --volume /docker-user-mirror/volume/ --workdir /docker-user-mirror/ "$IMAGE_NAME" sh -c 'true';
+IMAGE_NAME="$(pwd | xargs basename)"
+$CONTAINER_ENGINE build -t "$IMAGE_NAME" image/
+./user-mirror $CONTAINER_ENGINE run --rm -v ./:/docker-user-mirror --volume /docker-user-mirror/volume/ --workdir /docker-user-mirror/ "$IMAGE_NAME" sh -c 'true'
 
 # Test directory exists
 if ! [ -d volume ]; then
-    printf 'directory "%s" not found\n' 'volume' >&2;
-    exit 1;
+    printf 'directory "%s" not found\n' 'volume' >&2
+    exit 1
 fi
 
 # Test file ownership matches the current user
-directory_owner_uid=$(stat -c "%u" volume);
-directory_owner_gid=$(stat -c "%g" volume);
-user_uid=$(id -u);
-user_gid=$(id -g);
+directory_owner_uid=$(stat -c "%u" volume)
+directory_owner_gid=$(stat -c "%g" volume)
+user_uid=$(id -u)
+user_gid=$(id -g)
 if ! [ $directory_owner_uid -eq $user_uid ]; then
-    printf 'Ownership UID for "volume" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2;
-    exit 1;
+    printf 'Ownership UID for "volume" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2
+    exit 1
 fi
 if ! [ $directory_owner_gid -eq $user_gid ]; then
-    printf 'Ownership GID for "volume" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2;
-    exit 1;
+    printf 'Ownership GID for "volume" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2
+    exit 1
 fi
diff --git a/test/multi-container-test b/test/multi-container-test
--- a/test/multi-container-test
+++ b/test/multi-container-test
@@ -1,13 +1,13 @@
 #!/bin/sh
-THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
-. "$THIS_SCRIPT_DIR/../scripts/test-utilities";
+THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
+. "$THIS_SCRIPT_DIR/../scripts/test-utilities"
 
 # Skip on Podman
 if [ "$CONTAINER_ENGINE" = 'podman' ]; then
-    exit 0;
+    exit 0
 fi
 
-mv compose.yml compose1.yml;
+mv compose.yml compose1.yml
 cat <<EOF > compose2.yml
 services:
   a:
@@ -24,47 +24,47 @@ services:
       - ./:/docker-user-mirror/b
 EOF
 
-$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config --no-normalize -o compose.yml;
-rm compose1.yml;
-rm compose2.yml;
+$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config --no-normalize -o compose.yml
+rm compose1.yml
+rm compose2.yml
 
-$COMPOSE_ENGINE build;
-./user-mirror $COMPOSE_ENGINE up --detach a b;
-$COMPOSE_ENGINE down;
+$COMPOSE_ENGINE build
+./user-mirror $COMPOSE_ENGINE up --detach a b
+$COMPOSE_ENGINE down
 
 # Test directory exists
 if ! [ -d a ]; then
-    printf 'directory "%s" not found\n' 'a' >&2;
-    exit 1;
+    printf 'directory "%s" not found\n' 'a' >&2
+    exit 1
 fi
 
 # Test directory exists
 if ! [ -d b ]; then
-    printf 'directory "%s" not found\n' 'b' >&2;
-    exit 1;
+    printf 'directory "%s" not found\n' 'b' >&2
+    exit 1
 fi
 
 # Test file ownership matches the current user
-user_uid=$(id -u);
-user_gid=$(id -g);
-directory_owner_uid=$(stat -c "%u" a);
-directory_owner_gid=$(stat -c "%g" a);
+user_uid=$(id -u)
+user_gid=$(id -g)
+directory_owner_uid=$(stat -c "%u" a)
+directory_owner_gid=$(stat -c "%g" a)
 if ! [ $directory_owner_uid -eq $user_uid ]; then
-    printf 'Ownership UID for "a" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2;
-    exit 1;
+    printf 'Ownership UID for "a" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2
+    exit 1
 fi
 if ! [ $directory_owner_gid -eq $user_gid ]; then
-    printf 'Ownership GID for "a" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2;
-    exit 1;
+    printf 'Ownership GID for "a" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2
+    exit 1
 fi
 
-directory_owner_uid=$(stat -c "%u" b);
-directory_owner_gid=$(stat -c "%g" b);
+directory_owner_uid=$(stat -c "%u" b)
+directory_owner_gid=$(stat -c "%g" b)
 if ! [ $directory_owner_uid -eq $user_uid ]; then
-    printf 'Ownership UID for "b" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2;
-    exit 1;
+    printf 'Ownership UID for "b" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2
+    exit 1
 fi
 if ! [ $directory_owner_gid -eq $user_gid ]; then
-    printf 'Ownership GID for "b" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2;
-    exit 1;
+    printf 'Ownership GID for "b" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2
+    exit 1
 fi
diff --git a/test/volume-host-test b/test/volume-host-test
--- a/test/volume-host-test
+++ b/test/volume-host-test
@@ -1,8 +1,8 @@
 #!/bin/sh
-THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
-. "$THIS_SCRIPT_DIR/../scripts/test-utilities";
+THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
+. "$THIS_SCRIPT_DIR/../scripts/test-utilities"
 
-mv compose.yml compose1.yml;
+mv compose.yml compose1.yml
 cat <<EOF > compose2.yml
 services:
   sh:
@@ -14,29 +14,29 @@ volumes:
   volume:
 EOF
 
-$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config > compose.yml;
-rm compose1.yml;
-rm compose2.yml;
+$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config > compose.yml
+rm compose1.yml
+rm compose2.yml
 
-$COMPOSE_ENGINE build;
-./user-mirror $COMPOSE_ENGINE run --rm sh -c 'true';
+$COMPOSE_ENGINE build
+./user-mirror $COMPOSE_ENGINE run --rm sh -c 'true'
 
 # Test directory exists
 if ! [ -d volume ]; then
-    printf 'directory "%s" not found\n' 'volume' >&2;
-    exit 1;
+    printf 'directory "%s" not found\n' 'volume' >&2
+    exit 1
 fi
 
 # Test file ownership matches the current user
-directory_owner_uid=$(stat -c "%u" volume);
-directory_owner_gid=$(stat -c "%g" volume);
-user_uid=$(id -u);
-user_gid=$(id -g);
+directory_owner_uid=$(stat -c "%u" volume)
+directory_owner_gid=$(stat -c "%g" volume)
+user_uid=$(id -u)
+user_gid=$(id -g)
 if ! [ $directory_owner_uid -eq $user_uid ]; then
-    printf 'Ownership UID for "volume" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2;
-    exit 1;
+    printf 'Ownership UID for "volume" does not match (expected %s, got %s)\n' $user_uid $directory_owner_uid >&2
+    exit 1
 fi
 if ! [ $directory_owner_gid -eq $user_gid ]; then
-    printf 'Ownership GID for "volume" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2;
-    exit 1;
+    printf 'Ownership GID for "volume" does not match (expected %s, got %s)\n' $user_gid $directory_owner_gid >&2
+    exit 1
 fi
