Add automatic volume scanning

diff --git a/src/user-mirror-args b/src/user-mirror-args
--- a/src/user-mirror-args
+++ b/src/user-mirror-args
@@ -1,6 +1,13 @@
 #!/bin/sh
 set -eC;
 
+get_volumes() {
+    if $COMPOSE_ENGINE --progress quiet create --force-recreate >/dev/null 2>&1; then
+        $CONTAINER_ENGINE inspect --format '{{range .Mounts}}{{if eq .Type "volume"}}"{{print .Destination}}" {{end}}{{end}}' \
+            "$($COMPOSE_ENGINE --progress quiet ps -a --format '{{.ID}}')";
+    fi
+}
+
 # Parse options
 while [ $# -gt 0 ]; do
     case $1 in
@@ -19,6 +26,33 @@ while [ $# -gt 0 ]; do
     esac
     shift;
 done
+
+if [ "$o_podman" = true ]; then
+    CONTAINER_ENGINE='podman';
+    if podman compose version >/dev/null 2>&1; then
+        COMPOSE_ENGINE='podman compose';
+    elif podman-compose version >/dev/null 2>&1; then
+        COMPOSE_ENGINE='podman-compose';
+    else
+        printf 'Could not find a Podman Compose engine.\n' >&2;
+        exit 1;
+    fi
+else
+    CONTAINER_ENGINE='docker';
+    if docker compose version >/dev/null 2>&1; then
+        COMPOSE_ENGINE='docker compose'
+    elif docker-compose version >/dev/null 2>&1; then
+        COMPOSE_ENGINE='docker-compose'
+    else
+        printf 'Could not find a Docker Compose engine.\n' >&2;
+        exit 1;
+    fi
+fi
+
+VOLUMES="$(get_volumes)";
+if [ -n "$VOLUMES" ]; then
+    printf -- "CHOWN='%s'" "$VOLUMES";
+fi
 
 if [ "$o_podman" = true ] || docker info -f '{{println .SecurityOptions}}' | grep 'rootless' 1>/dev/null; then
     printf -- '--env GID=%s ' '0';
